# Generated by Django 6.0.1 on 2026-02-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_contactmessage_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
