# Generated by Django 6.0.1 on 2026-02-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_cause_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=100)),
                ('availability', models.CharField(choices=[('WEEKDAYS', 'Weekdays'), ('WEEKENDS', 'Weekends'), ('BOTH', 'Both Weekdays and Weekends'), ('FLEXIBLE', 'Flexible')], max_length=100)),
                ('skills', models.CharField(max_length=255)),
                ('reason', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')]),
        ),
    ]
