# Generated by Django 6.0.1 on 2026-03-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_donation_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='uploads/'),
        ),
    ]
