# Generated by Django 6.0.1 on 2026-03-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_alter_post_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='donor_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='amount',
            new_name='final_amount',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='donor_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='donation',
            name='custom_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='selected_amount',
            field=models.IntegerField(blank=True, choices=[(500, '₹500'), (1000, '₹1000'), (2500, '₹2500'), (5000, '₹5000'), (10000, '₹10000'), (25000, '₹25000')], null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
