# Generated by Django 6.0.1 on 2026-02-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_add_image_url_to_cause'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('file_image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('url_image', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
