# Generated by Django 6.0.1 on 2026-03-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_rename_donor_email_donation_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='region',
            field=models.CharField(choices=[('India', 'India'), ('International', 'International')], default='Unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='uploaded_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
