# Generated by Django 6.0.1 on 2026-03-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_donation_region_donation_uploaded_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='payment_id',
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=20),
        ),
    ]
