# Generated by Django 6.0.1 on 2026-04-02 11:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_alter_cause_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='uploaded_receipt',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
