# Generated by Django 6.0.1 on 2026-02-09 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 9, 12, 48, 44, 453586, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
