# Generated by Django 6.0.1 on 2026-02-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_contactmessage_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Education', 'Education'), ('Health', 'Health'), ('Food', 'Food'), ('Environment', 'Environment'), ('Shelter', 'Shelter')], max_length=100)),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('featured', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('short_description', models.CharField(max_length=255)),
                ('full_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
