# Generated by Django 6.0.1 on 2026-02-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_cause'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('image', models.URLField(blank=True, max_length=500)),
                ('content', models.TextField()),
            ],
        ),
    ]
