# Generated by Django 6.0.1 on 2026-02-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_testimonial_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
