# Generated by Django 6.0.1 on 2026-02-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_testimonial_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
