# Generated by Django 6.0.1 on 2026-02-12 06:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_volunteer_alter_testimonial_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
