# Generated by Django 6.0.1 on 2026-02-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='age',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
    ]
