# Generated by Django 6.0.1 on 2026-02-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_volunteer_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('category_name', models.CharField(max_length=100)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
